"""Translate English product titles to Chinese for 1688 search.

Two-phase approach:
1. Multi-word phrases first (longer = more specific = higher priority)
2. Single words with word-boundary matching (avoid "ball" inside "football")
"""
import re

# Multi-word phrases (checked first, longer phrases get priority)
PHRASE_MAP = {
    # Sports & Events
    "football world cup": "足球世界杯",
    "world cup": "世界杯",
    "wall chart": "海报",
    "wall poster": "墙贴海报",
    "scratch remover": "划痕修复剂",
    "trim restorer": "塑料件修复剂",
    "headlight restorer": "大灯翻新剂",
    "car polish": "汽车抛光剂",
    "car wax": "汽车蜡",
    "tyre inflator": "轮胎充气泵",
    "tire pressure": "胎压",
    "phone holder": "手机支架",
    "phone mount": "手机支架",
    "phone stand": "手机支架",
    "car phone": "车载手机",
    "screen protector": "屏幕保护膜",
    "tempered glass": "钢化膜",
    "ear buds": "耳机",
    "charging cable": "充电线",
    "usb c": "Type-C",
    "usb cable": "USB数据线",
    "led strip": "LED灯带",
    "led light": "LED灯",
    "night light": "夜灯",
    "fairy lights": "装饰灯串",
    "string lights": "灯串",
    "solar light": "太阳能灯",
    "solar garden": "太阳能花园",
    "garden light": "花园灯",
    "desk lamp": "台灯",
    "table lamp": "台灯",
    "floor lamp": "落地灯",
    "reading light": "阅读灯",
    "book light": "书灯",
    "clip light": "夹子灯",
    "spice rack": "调料架",
    "dish rack": "碗碟架",
    "drying rack": "晾干架",
    "shoe rack": "鞋架",
    "wine rack": "酒架",
    "towel rail": "毛巾架",
    "toilet brush": "马桶刷",
    "shower caddy": "浴室置物架",
    "soap dispenser": "洗手液器",
    "bathroom shelf": "浴室置物架",
    "kitchen organizer": "厨房收纳",
    "drawer divider": "抽屉分隔",
    "cable management": "理线器",
    "cable clip": "线夹",
    "cable tie": "扎带",
    "under bed": "床底收纳",
    "wardrobe organiser": "衣柜收纳",
    "storage box": "收纳盒",
    "storage bag": "收纳袋",
    "storage basket": "收纳篮",
    "makeup bag": "化妆包",
    "makeup brush": "化妆刷",
    "makeup mirror": "化妆镜",
    "nail art": "美甲",
    "hair clip": "发夹",
    "hair tie": "发圈",
    "hair band": "发带",
    "hair accessories": "发饰",
    "resistance band": "弹力带",
    "yoga mat": "瑜伽垫",
    "foam roller": "泡沫轴",
    "jump rope": "跳绳",
    "gym bag": "健身包",
    "dog toy": "狗玩具",
    "cat toy": "猫玩具",
    "dog bed": "狗窝",
    "cat bed": "猫窝",
    "dog collar": "狗项圈",
    "cat collar": "猫项圈",
    "dog lead": "狗牵引绳",
    "dog harness": "狗胸背带",
    "pet grooming": "宠物美容",
    "pet feeder": "宠物喂食器",
    "pet water": "宠物饮水器",
    "bird feeder": "喂鸟器",
    "garden tool": "园艺工具",
    "plant pot": "花盆",
    "hose nozzle": "水管喷头",
    "garden kneeler": "园艺跪垫",
    "bbq grill": "烧烤架",
    "camping tent": "露营帐篷",
    "sleeping bag": "睡袋",
    "car boot": "后备箱",
    "boot organiser": "后备箱收纳",
    "seat gap": "座椅缝隙",
    "car sun shade": "汽车遮阳帘",
    "car organiser": "车载收纳",
    "car vacuum": "车载吸尘器",
    "air freshener": "空气清新剂",
    "wall hook": "墙壁挂钩",
    "adhesive hook": "粘贴挂钩",
    "photo frame": "相框",
    "picture frame": "画框",
    "candle holder": "烛台",
    "artificial plant": "仿真植物",
    "artificial flower": "仿真花",
    "wall shelf": "墙上置物架",
    "floating shelf": "浮动搁架",
    "monitor stand": "显示器支架",
    "laptop stand": "笔记本支架",
    "desk organiser": "桌面收纳",
    "pen holder": "笔筒",
    "label maker": "标签机",
    "water bottle": "水壶",
    "sports bottle": "运动水壶",
    "food container": "保鲜盒",
    "lunch box": "午餐盒",
    "ice cream": "冰淇淋",
    "garlic press": "压蒜器",
    "vegetable peeler": "削皮器",
    "oil dispenser": "油壶",
    "measuring cup": "量杯",
    "measuring spoon": "量勺",
    "silicone utensil": "硅胶厨具",
    "wine opener": "开瓶器",
    "bottle opener": "开瓶器",
    "can opener": "开罐器",
    "cake tin": "蛋糕模具",
    "baking tray": "烤盘",
    "oven glove": "隔热手套",
    "tea towel": "茶巾",
    "washing up": "洗碗",
    "cleaning cloth": "抹布",
    "microfiber cloth": "超细纤维布",
    "lint roller": "粘毛器",
    "duster extendable": "伸缩除尘器",
    "grout brush": "缝隙刷",
    "drain cover": "地漏盖",
    "door stop": "门挡",
    "door handle": "门把手",
    "drawer pull": "抽屉拉手",
    "wall clock": "挂钟",
    "alarm clock": "闹钟",
    "key ring": "钥匙扣",
    "money box": "存钱罐",
    "piggy bank": "存钱罐",
    "photo album": "相册",
    "washi tape": "和纸胶带",
    "vinyl sticker": "贴纸",
    "paint brush": "画笔",
    "craft knife": "美工刀",
    "cutting mat": "切割垫",
    "sewing kit": "缝纫套装",
    "first aid": "急救",
    "pill box": "药盒",
    "eye mask": "眼罩",
    "sleep mask": "睡眠眼罩",
    "wrist rest": "腕托",
    "mouse pad": "鼠标垫",
    "webcam cover": "摄像头遮挡",
    "laptop sleeve": "笔记本内胆包",
    "power bank": "充电宝",
    "wireless charger": "无线充电器",
    "car charger": "车载充电器",
    "wall charger": "墙插充电器",
    "plug adapter": "插头转换器",
    "travel adapter": "旅行转换器",
    "extension lead": "排插",
    "extension cable": "延长线",
    "smart plug": "智能插座",
    "motion sensor": "人体感应",
    "door bell": "门铃",
    "security camera": "监控摄像头",
    "baby gate": "婴儿门栏",
    "corner protector": "防撞角",
    "cabinet lock": "柜子锁",
    "toilet seat": "马桶盖",
    "shower head": "花洒",
    "bath mat": "浴室垫",
    "non slip mat": "防滑垫",
    "splash guard": "挡水板",
    "window cleaner": "擦窗器",
    "glass cleaner": "玻璃清洁器",
    "pet treat": "宠物零食",
    "dog chew": "狗咬胶",
    "cat scratch": "猫抓板",
    "litter tray": "猫砂盆",
    "aquarium filter": "鱼缸过滤器",
    "fish tank": "鱼缸",
    "food wrap": "保鲜膜",
    "reusable food wrap": "硅胶保鲜膜",
    "beeswax wrap": "蜂蜡保鲜布",
    "washi tape": "和纸胶带",
    "vinyl sticker": "贴纸",
    "wall shelf": "墙上置物架",
    "art supplies": "美术用品",
    "craft supplies": "手工用品",
    "face roller": "面部按摩滚轮",
}

# Single words with word-boundary matching
WORD_MAP = {
    # Electronics
    "charger": "充电器",
    "cable": "数据线",
    "adapter": "适配器",
    "hub": "集线器",
    "stand": "支架",
    "holder": "支架",
    "mount": "支架",
    "dock": "扩展坞",
    "case": "保护壳",
    "cover": "保护套",
    "protector": "保护膜",
    "headphones": "耳机",
    "earbuds": "耳机",
    "speaker": "音箱",
    "microphone": "麦克风",
    "webcam": "摄像头",
    "keyboard": "键盘",
    "mouse": "鼠标",
    "router": "路由器",
    "modem": "调制解调器",
    "printer": "打印机",
    "scanner": "扫描仪",
    "tablet": "平板",
    "stylus": "触控笔",
    "tracker": "追踪器",
    "sensor": "传感器",
    "switch": "开关",
    "remote": "遥控器",
    "timer": "定时器",
    "thermometer": "温度计",
    "hygrometer": "湿度计",
    "barometer": "气压计",
    "scale": "秤",
    "calculator": "计算器",

    # Lighting
    "light": "灯",
    "led": "LED灯",
    "lamp": "台灯",
    "strip": "灯带",
    "bulb": "灯泡",
    "lantern": "灯笼",
    "torch": "手电筒",
    "spotlight": "聚光灯",

    # Home & Kitchen
    "organizer": "收纳盒",
    "organiser": "收纳盒",
    "storage": "收纳",
    "basket": "篮子",
    "shelf": "架子",
    "rack": "架子",
    "hook": "挂钩",
    "hanger": "衣架",
    "container": "容器",
    "bottle": "瓶子",
    "flask": "保温杯",
    "tumbler": "水杯",
    "thermos": "保温壶",
    "jug": "水壶",
    "pitcher": "水壶",
    "carafe": "水瓶",
    "cup": "杯子",
    "mug": "马克杯",
    "plate": "盘子",
    "bowl": "碗",
    "saucer": "碟子",
    "knife": "刀",
    "scissors": "剪刀",
    "tool": "工具",
    "brush": "刷子",
    "sponge": "海绵",
    "towel": "毛巾",
    "mat": "垫子",
    "rug": "地毯",
    "curtain": "窗帘",
    "pillow": "枕头",
    "cushion": "靠垫",
    "blanket": "毯子",
    "throw": "披毯",
    "duvet": "被子",
    "sheet": "床单",
    "quilt": "被子",
    "apron": "围裙",
    "mitt": "手套",
    "spatula": "铲子",
    "whisk": "打蛋器",
    "tongs": "夹子",
    "colander": "滤网",
    "strainer": "滤网",
    "grater": "刨丝器",
    "peeler": "削皮器",
    "opener": "开瓶器",
    "corkscrew": "开瓶器",
    "funnel": "漏斗",
    "sieve": "筛子",
    "ladle": "汤勺",
    "spoon": "勺子",
    "fork": "叉子",
    "chopsticks": "筷子",
    "coaster": "杯垫",
    "placemat": "餐垫",
    "tray": "托盘",
    "bin": "垃圾桶",

    # Cleaning
    "mop": "拖把",
    "broom": "扫帚",
    "dustpan": "簸箕",
    "bucket": "桶",
    "spray": "喷雾",
    "nozzle": "喷头",
    "squeegee": "刮水器",

    # Bathroom
    "shower": "花洒",
    "taps": "水龙头",
    "faucet": "水龙头",
    "mirror": "镜子",
    "razor": "剃须刀",
    "trimmer": "修剪器",
    "shaver": "剃须刀",
    "comb": "梳子",
    "cotton": "棉",
    "swab": "棉签",

    # Fashion & Accessories
    "bag": "包",
    "wallet": "钱包",
    "purse": "钱包",
    "pouch": "小包",
    "belt": "皮带",
    "watch": "手表",
    "ring": "戒指",
    "necklace": "项链",
    "bracelet": "手链",
    "earring": "耳环",
    "glasses": "眼镜",
    "sunglasses": "太阳镜",
    "hat": "帽子",
    "cap": "帽子",
    "scarf": "围巾",
    "gloves": "手套",
    "socks": "袜子",
    "umbrella": "雨伞",
    "keychain": "钥匙扣",

    # Sports & Outdoor
    "yoga": "瑜伽",
    "ball": "球",
    "rope": "绳子",
    "band": "弹力带",
    "weight": "哑铃",
    "dumbbell": "哑铃",
    "kettlebell": "壶铃",
    "tent": "帐篷",
    "backpack": "背包",
    "filter": "滤水器",
    "compass": "指南针",
    "binoculars": "望远镜",
    "kayak": "皮划艇",
    "paddle": "桨",
    "hookah": "水烟",

    # Pet Supplies
    "leash": "牵引绳",
    "collar": "项圈",
    "harness": "胸背带",
    "toy": "玩具",
    "bed": "宠物床",
    "feeder": "喂食器",
    "scratching": "猫抓",
    "grooming": "美容",
    "clippers": "指甲剪",

    # Office & Stationery
    "pen": "笔",
    "pencil": "铅笔",
    "notebook": "笔记本",
    "journal": "手账",
    "diary": "日记本",
    "planner": "计划本",
    "paper": "纸",
    "tape": "胶带",
    "glue": "胶水",
    "sticker": "贴纸",
    "marker": "记号笔",
    "highlighter": "荧光笔",
    "eraser": "橡皮",
    "ruler": "尺子",
    "stapler": "订书机",
    "punch": "打孔器",
    "clip": "夹子",
    "pin": "图钉",
    "washi": "和纸",
    "envelope": "信封",
    "folder": "文件夹",
    "binder": "活页夹",
    "label": "标签",
    "stamp": "印章",
    "ink": "墨水",

    # Car & Motorcycle
    "car": "汽车",
    "motorcycle": "摩托车",
    "bike": "自行车",
    "tire": "轮胎",
    "tyre": "轮胎",
    "wheel": "轮子",
    "seat": "座椅",
    "visor": "遮阳板",
    "bumper": "保险杠",
    "mudguard": "挡泥板",
    "wiper": "雨刷",
    "antenna": "天线",
    "exhaust": "排气管",

    # Garden & Outdoor
    "plant": "植物",
    "pot": "花盆",
    "seed": "种子",
    "soil": "土壤",
    "fertilizer": "肥料",
    "watering": "浇水",
    "hose": "水管",
    "sprinkler": "喷头",
    "fence": "栅栏",
    "bird": "鸟",
    "insect": "虫",
    "mosquito": "蚊子",
    "repellent": "驱虫",
    "trap": "捕",
    "solar": "太阳能",
    "bbq": "烧烤",
    "grill": "烤架",
    "cooler": "冷藏箱",
    "picnic": "野餐",
    "camping": "露营",
    "hammock": "吊床",
    "swing": "秋千",

    # Baby & Kids
    "rattle": "摇铃",
    "teether": "磨牙棒",
    "bib": "围嘴",
    "potty": "坐便器",

    # Materials
    "stainless": "不锈钢",
    "silicone": "硅胶",
    "leather": "皮革",
    "velvet": "天鹅绒",
    "wool": "羊毛",
    "linen": "亚麻",
    "bamboo": "竹",
    "wooden": "木",
    "acrylic": "亚克力",
    "resin": "树脂",
    "ceramic": "陶瓷",
    "porcelain": "瓷器",
    "marble": "大理石",
    "granite": "花岗岩",
    "cork": "软木",
    "latex": "乳胶",
    "memory foam": "记忆棉",
    "mesh": "网布",
    "canvas": "帆布",
    "denim": "牛仔",
    "suede": "麂皮",

    # Colors
    "black": "黑色",
    "white": "白色",
    "red": "红色",
    "blue": "蓝色",
    "green": "绿色",
    "yellow": "黄色",
    "pink": "粉色",
    "purple": "紫色",
    "orange": "橙色",
    "brown": "棕色",
    "gray": "灰色",
    "grey": "灰色",
    "gold": "金色",
    "silver": "银色",
    "navy": "藏青",
    "beige": "米色",
    "khaki": "卡其色",
    "teal": "蓝绿",

    # Common descriptors
    "portable": "便携",
    "mini": "迷你",
    "compact": "紧凑",
    "foldable": "可折叠",
    "collapsible": "可折叠",
    "adjustable": "可调节",
    "waterproof": "防水",
    "rechargeable": "可充电",
    "magnetic": "磁吸",
    "rotating": "旋转",
    "multi": "多功能",
    "professional": "专业",
    "premium": "高端",
    "vintage": "复古",
    "retro": "复古",
    "boho": "波西米亚",
    "rustic": "乡村风",
    "elegant": "优雅",
    "luxury": "豪华",

    # Sizes/units
    "large": "大号",
    "small": "小号",
    "medium": "中号",
    "jumbo": "超大号",
    "micro": "微型",
    "set": "套装",
    "pack": "包装",
    "kit": "套装",
    "bundle": "组合",
    "pair": "对",
    "piece": "件",
    "unit": "个",
    "lot": "批",

    # Official/branded items
    "official": "官方",
    "licensed": "授权",
    "merchandise": "周边",
    "souvenir": "纪念品",
    "memorabilia": "纪念品",
    "collectible": "收藏品",
    "figurine": "手办",
    "decal": "贴花",
    "sticker": "贴纸",
    "badge": "徽章",
    "pin": "胸针",
    "magnet": "冰箱贴",
    "seasonal": "季节性",
    "birthday": "生日",
    "gift": "礼品",
    "party": "派对",
    "decoration": "装饰",
    "festive": "节日",
    "christmas": "圣诞",
    "halloween": "万圣节",
    "easter": "复活节",
    "toilet": "马桶",
}


def translate_title_to_chinese(title: str) -> str:
    """Translate English product title to Chinese keywords for 1688 search.

    Phase 1: Multi-word phrase matching (longest first, word-boundary)
    Phase 2: Single-word matching (word-boundary to avoid substring hits)
    Phase 3: Fallback to original English words
    """
    if not title:
        return ""

    title_lower = title.lower()
    chinese_keywords = []
    matched_spans = []  # Track matched character ranges

    def is_overlapping(start, end):
        for ms, me in matched_spans:
            if start < me and end > ms:
                return True
        return False

    def try_match(pattern, replacement):
        """Word-boundary regex match."""
        m = re.search(pattern, title_lower)
        if m and not is_overlapping(m.start(), m.end()):
            matched_spans.append((m.start(), m.end()))
            chinese_keywords.append(replacement)
            return True
        return False

    # Phase 1: Multi-word phrases (sorted longest first)
    for phrase, cn in sorted(PHRASE_MAP.items(), key=lambda x: -len(x[0])):
        pattern = r'(?<![a-z])' + re.escape(phrase) + r'(?![a-z])'
        try_match(pattern, cn)

    # Phase 2: Single words with word boundaries
    for word, cn in sorted(WORD_MAP.items(), key=lambda x: -len(x[0])):
        if ' ' in word:
            continue  # Skip multi-word in this phase
        pattern = r'(?<![a-z])' + re.escape(word) + r'(?![a-z])'
        try_match(pattern, cn)

    # Deduplicate
    seen = set()
    unique = []
    for kw in chinese_keywords:
        if kw not in seen:
            seen.add(kw)
            unique.append(kw)

    if unique:
        return " ".join(unique[:5])

    # Fallback: return original English title (better than gibberish Chinese)
    words = [w for w in title.split() if len(w) > 2]
    return " ".join(words[:5])


if __name__ == "__main__":
    tests = [
        "Giftinghouse Official Football World Cup 2026 Wall Chart Poster",
        "Car Phone Holder Mount Dashboard",
        "Stainless Steel Water Bottle 700ml",
        "Dog Chew Toy Rope Knot",
        "Kitchen Spice Rack Organizer",
        "LED Strip Lights USB Powered",
        "Silicone Phone Case for iPhone 15 Pro Max",
        "Scratch Remover Compound for Cars",
        "Trim Restorer Plastic Gel",
        "USB C Charger 20W Fast Charging Adapter",
        "Yoga Mat Non-Slip Exercise Fitness",
        "Wireless Bluetooth Earbuds Headphones",
        "Cable Management Box Under Desk",
        "Solar Garden Light Outdoor Waterproof",
        "Cat Scratching Post Tree Tower",
    ]
    for t in tests:
        print(f"{t}")
        print(f"  → {translate_title_to_chinese(t)}")
        print()
